import {StyleSheet} from 'react-native';
import { COLORS } from '../../constant/Colors';
import { FONTS } from '../../constant/Fonts';

const GlobalStyles = StyleSheet.create({
    topTab: {
      color:'#1F9CEF',
    },
    tabScreens: {
      color:'#1F9CEF',
    },
    tabBarStyle:{
      backgroundColor:'#1F9CEF',
    },
    mainContainer: { 
        flex:1,
        alignItems: 'center', 
        width: '100%',
        margin:0,
        padding:10,
      },
      scrollViewBG:{
        backgroundColor: COLORS.white,
      },
      signupContainer: {
        backgroundColor: '#F6F8FC',
        flex:1,
        width: '100%',
        margin:0,
        padding:0,
      },
      backgrey: {
        backgroundColor: '#F6F8FC',
        margin:15,
        marginTop:5,
        
      },
      signupTitle: {
        height: 60,
        backgroundColor: '#fff',
        width:'100%',
        padding: 10,
      },
      signupTitleStyle: {
        fontFamily: FONTS.SemiBold,
        textAlign: 'center', 
        fontSize: 20,
      },
      signupParagraph: {
        textAlign: 'left',
        paddingTop: 20,
        left:0,
        paddingLeft:15,
        paddingBottom:20,
        fontSize:14,
        fontFamily: FONTS.Medium,
        color:'#546471',
      },
      signupInputContainer: {
        padding: 15,
        backgroundColor:COLORS.white,
        marginBottom:0,
        paddingBottom:0,
        paddingTop:10,
      },
      signupTextInput: {
        fontSize: 16,
      },
      signupLabel: {
        fontSize:14,
        paddingBottom: 5,
        color: COLORS.loginTextInput,
        fontFamily: FONTS.Medium,
      },
      countryCodeSection: {
        width:'41%',
        marginRight:'2%',
        marginTop:26,
        paddingTop:4,
        marginBottom: 10,
        marginLeft:0,
      },
      mobileNoSection: {
        width:'50%',
        marginLeft:'2%',
        paddingTop:0,
        marginBottom: 10,
        height:46,
      },
      dropdownContainer: {  
        borderWidth:1, 
        borderColor:'#000', 
        borderRadius:5,
        height: 46,
      },
      signupPasswordInput: {
        fontSize: 16,
        width:'85%',
      },
      uploadContainer: {
        borderWidth: 1,
        borderStyle:'dashed',
        borderColor:'#000',
        textAlign:'center',
        padding:5,
        borderRadius:5,
        backgroundColor:'#F7F9FA',
        paddingBottom:0,
        paddingTop:25,
        height:150,
      },
      iconStyle: {
        justifyContent: 'center',
        alignSelf:'center',
        paddingBottom:10,

      },
      uploadContainerFirstText: {
        textAlign: 'center',
        paddingTop:15,
        color:'#0F141A',
        fontSize:15,
        paddingBottom:2,
      },
      uploadContainerBottomText: {
        textAlign: 'center',
        color:'#546471',
        fontSize:12,
        paddingBottom:0,
        marginBottom:0,
      },
      buttonStyle: {
        padding: 10,
        paddingLeft:35,
        paddingRight:35,
        backgroundColor:COLORS.white,
        fontSize:16,
        backgroundColor: COLORS.button,
        textAlign: 'center',
        color:COLORS.theme,
        borderRadius:6,
        marginLeft:30,
        marginRight:30,
      }, 
      buttonStyleRounded: {
        padding: 20,
        paddingLeft:35,
        paddingRight:35,
        backgroundColor: COLORS.button,
        textAlign: 'center',
        color:COLORS.theme,
        borderRadius:6,
        marginTop:15,
        borderRadius:10,
      },
      buttonStyleRoundedText: {
        fontSize:18,
        color:COLORS.theme,
        fontFamily:FONTS.SemiBold,
        textAlign: 'center',
      },
      button: {
        shadowColor: '#171717',
        shadowOffset: {width: 0, height: -4},
        shadowOpacity: 0.2,
        shadowRadius: 3,
      },


      container: {
         marginTop: 60,
         margin:0,
         paddingLeft:20,
         paddingRight:20,
      },
      inputView : {
        marginBottom:7,
        marginTop:5,
      },
      mrgnBtn:{
        marginBottom:12,
      },
      signinPasswordInputView: {
        width:'95%',
        marginBottom:0,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft:10,
        marginRight:10,
      },
      logo:{
        paddingTop:0,
        marginTop:65,
        width: 185,
        height: 120,
        top:0,
        alignItems: 'center',
        justifyContent: 'center',
      },
      inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        //borderColor:COLORS.textInputBorder,
        borderWidth: 1,
        borderRadius:5,
        width:'100%',
         padding: 5,
          //marginBottom: 10,
          paddingLeft:10,
        height: 45,
        fontSize:18,
      },
      inputTextareaSection: {
        marginLeft:4,
        marginRight:4,
      },
      inputTextarea: {
        //borderColor:COLORS.textInputBorder,
        borderWidth: 1,
        borderRadius:5,
        width:'100%',
      },
      rowTwoInput:{
        width:'100%',
        display:'flex',
        flexDirection:'row',
        margin:0,
      },
      imageIcon: {
        width: '100%',
        //height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        display: 'flex',
        flexDirection: 'row',
        //flexWrap: 'wrap',
        padding:0,
        margin:0,
        marginRight:100,
      },
      imageBox:{
        alignItems: 'center',
        justifyContent: 'center',
        margin:5,
        width: 100,
        height: 60,
        backgroundColor: '#F7F9FA',
        borderRadius:6,
      },
      logoIcon:{
        alignItems: 'center',
        justifyContent: 'center',
        width: 10,
        height: 10,
        //backgroundColor: '#F7F9FA',
        marginLeft:10,
        marginRight:10,
        padding:10,
      },
      titleStyle:{
        textAlign: 'center', 
        fontSize: 22,
        marginTop: 0,
        paddingBottom:5,
        fontFamily: FONTS.Bold,
      },
      paragraphStyle: {
        marginBottom:40,
        textAlign: 'center',
        fontSize: 15,
        color: COLORS.loginText,
        fontFamily: FONTS.Regular,
      },
      textInput:{
        //paddingLeft:12,
        width: '100%',
        borderRadius: 5,
        margin: 'auto',
        fontSize:22
      },
      TextInput: {
        fontSize: 16,
      },
      passwordIcon:{
        justifyContent: 'flex-end',
        alignItems:'flex-end',
        marginRight:0,
        textAlign:'right',
        
      },
      passwordInput:{
        width:'80%',
        fontSize: 15,
      },
      labelText:{
        fontSize:12,
        paddingBottom: 2,
        color: COLORS.loginTextInput,
        fontFamily: FONTS.Medium,
      },
      forgot_button: {
        textAlign:'right',
        fontSize: 13,
        color:COLORS.button,
        fontFamily: FONTS.Medium,
        paddingTop:0,
        marginTop:0,
      },
      loginBtn: {
        height: 45,
        width:'95%',
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.button,
        marginTop:15,
        marginBottom:15,
        borderRadius:5,
      },
      loginText:{
        width:'95%',
        color:COLORS.white,
        fontFamily: FONTS.Medium,
        fontSize: 15,
         textAlign: 'center', 
         padding: 10,  
      },
      labelSignin:{
        marginBottom:10,
      textAlign:'center',
      fontFamily: FONTS.Regular,
      color: '#7B868A'
      },
      newSignup:{
        marginTop: 30,
        alignItems: 'center',
        justifyContent: 'center',
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        fontSize:12,
      },
      account:{
        color:'#7B868A',
        fontFamily: FONTS.Regular,
      },
      new_sign:{
        color:COLORS.button,
        fontFamily: FONTS.Regular,
      },

      frontcontainer: {
        flex: 1,
        backgroundColor: COLORS.theme,
        alignItems: 'center',
        //padding: 10,
        justifyContent: 'center',
      },
      // titleStyle: {
      //   padding: 10,
      //   textAlign: 'center',
      //   fontSize: 18,
      //   fontWeight: 'bold',
      // },
      paragraphStyle: {
        padding: 20,
        textAlign: 'center',
        fontSize: 16,
      },
      introImageStyle: {
        width: 350,
        height: 450,
      },
      introTextStyle: {
        fontSize: 16,
        color: COLORS.introText,
        fontFamily: FONTS.Regular,
        textAlign: 'center',
        marginTop:40,
      },
      introTitleStyle: {
        fontSize: 20,
        fontFamily: FONTS.Bold,
        color: COLORS.introText,
        textAlign: 'center',
        fontWeight: 'bold',
        marginBottom:0,
        paddingBottom: 5,
        marginTop:40,
      },
      defaultScreenContainer: { 
        backgroundColor:'#F2F7FC',
        padding:16,
      },
      defaultScreenLabel:{
        color:'#5B6B65',
        fontSize:15,
        fontFamily:FONTS.Regular,
        paddingBottom:5,
      },
      defaultScreenDropdownContainer:{
        borderColor:'#DCDCDC',
        borderWidth:1,
        height:46,
        backgroundColor:'#fff',
        marginBottom:17,
      },
      defaultScreenInputContainer: {
        backgroundColor:'#F6F5F5',
        borderColor:'#DCDCDC',
        borderWidth:1,
      },
      defaultScreenInputWhiteContainer: {
        borderColor:'#DCDCDC',
        borderWidth:1,
      },
      defaultScreenCountryCodeSection:{
        width:'40%',
        paddingTop:5,
        marginBottom: 5,
        marginLeft:0,
      },
      defaultScreenMobileNoSection:{
        width:'60%',
        paddingTop:5,
        marginBottom: 5,
        marginLeft:0,
      },
      flexSection: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
      },
      checkboxContainer:{
        flexDirection: 'row',
        marginBottom: 5,
      },
      checkbox:{
        alignSelf: 'center',
      },
      checkboxLabel:{
        margin: 8,
        color:'#5B6B65',
        fontSize:13,
      },
      deliveryScreenContainer:{
        backgroundColor:'#F2F7FC',
        padding:16,
      },
      deliveryScreenSideDropdownContainer:{
        borderColor:'#DCDCDC',
        borderWidth:1,
        height:46,
        marginTop:28,
        backgroundColor:'white',
      },
      fullWidthDropDown:{
        width:'100%',
        backgroundColor:'white',
        marginBottom:20,
        borderColor:'#DCDCDC',
        borderWidth:1,
        height:46,
      },
      deliveryFlexSection:{
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        padding:0,
        margin:0,
      },
      checkboxSelectAllLabel:{
        color:'#1F222F',
        fontSize:14,
        margin:9,
      },
      deliveryFlexSectionLabels:{
        width: '90%',
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        padding:0,
        margin:0,
        justifyContent:'space-between',
        paddingStart:25,
        paddingRight:20,
        paddingTop:15,
      },
      deliveryFlexLabel:{
        color:'#9FA3AB',
        fontSize:13,
      },
      deliveryFeeScreenLabel:{
        color:'#5B6B65',
        fontSize:15,
        fontFamily:FONTS.Regular,
        paddingBottom:12,
        paddingTop:20,
        paddingLeft:10,
      },
      deliveryAreaScreenLabel:{
        color:'#5B6B65',
        fontSize:15,
        fontFamily:FONTS.Regular,
        marginTop:20,
        paddingBottom:8,
      },
      dayCheckboxContainer:{
        flexDirection: 'row',
        marginBottom: 5,
      },
      notificationDay:{
        color:'#1F9CEF',
        fontSize:15,
        fontFamily:FONTS.Regular,
        marginTop:20,
      },
      notificationOddContainer: {
        minHeight:100,
        width:'100%',
        borderColor:'#DCDCDC',
        backgroundColor:'white',
        borderWidth:1,
        marginTop:15,
        flexDirection:'row',
      },
      notificationEvenContainer: {
        minHeight:100,
        width:'100%',
        borderColor:'#DCDCDC',
        backgroundColor:'#F2F7FC',
        marginTop:15,
        borderWidth:1,
        flexDirection:'row',
      },
      invoiceNoMarginContainer: {
        minHeight:100,
        width:'100%',
        borderColor:'#DCDCDC',
        backgroundColor:'white',
        borderWidth:1,
        marginTop:0,
        flexDirection:'row',
      },
      invoiceSearchContainer: {
        minHeight:45,
        width:'100%',
        borderColor:'#DCDCDC',
        backgroundColor:'white',
        borderWidth:1,
        marginTop:15,
        flexDirection:'row',
        padding:10,
      },
      searchText: {
        width:'80%',
        marginLeft:10,
        fontSize:16,
        fontFamily:FONTS.Regular,
      },
      invoiceSearch: {
        paddingTop:10,
        padding:5
      },
      invoiceFilter: {
        height:35,
        width:35,
        backgroundColor:'#D0D6DD',
        padding:5,
        alignItems:'center',
      },
      notificationImageContainer: {
        width:40,
        marginTop:25,
        marginLeft:13,
      },
      notificationTextContainer: {
        width:'83%',
        marginLeft:13,
      },
      notificationTitle: {
        color:'#0F141A',
        fontSize:13,
        fontFamily:FONTS.SemiBold,
        marginTop:13,
      },
      notificationText: {
        color:'#1F222F',
        fontSize:13,
        fontFamily:FONTS.Regular,
        marginTop:5,
      },
      notificationDate: {
        color:'#617191',
        fontSize:13,
        fontFamily:FONTS.Regular,
        textAlign:'right',
        paddingRight:10,
        paddingBottom:10,
        marginTop:-10
      },
      notificationBell: {
        textAlign:'right',
        paddingRight:10,
        marginTop:-20
      },
      invoiceContainer: {
        width:'100%',
        padding:15,
      },
      
      invoiceTwoSectionRow: {
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        paddingBottom:5,
      },
      invoiceSingleSectionRow:{
        width:'100%',
        paddingBottom:5,
      },
      invoiceCardLeft: {
        width:250
      },
      invoiceCardRight: {
        width:100,
        alignContent:'flex-start',
      },
      invoiceTitle:{
        marginTop:5,
        fontFamily:FONTS.SemiBold,
        fontSize:16,
      },
      invoiceButtonPaid:{
        backgroundColor:'#36B152',
        borderWidth:1,
        borderColor:'#36B152',
        borderRadius:15,
        paddingVertical:4,
        paddingHorizontal:15,
      },
      invoiceButtonUnPaid:{
        backgroundColor:'#1F9CEF',
        borderWidth:1,
        borderColor:'#1F9CEF',
        borderRadius:15,
        paddingVertical:4,
        paddingHorizontal:15,
      },
      invoiceButtonText:{
        color:'#fff',
        fontSize:13,
        fontFamily:FONTS.SemiBold,
      },
      invoiceAddress:{
        color:'#617191',
        fontSize:14,
        fontFamily:FONTS.Regular,
      },
      billingAddress:{
        color:'#1F222F',
        fontSize:14,
        fontFamily:FONTS.Regular,
        lineHeight:20,
      },
      billingCurrency:{
        color:'#1F222F',
        fontSize:14,
        fontFamily:FONTS.Regular,
        lineHeight:20,
        paddingRight:20,
      },
      estimatedTotal:{
        color:'#1F9CEF',
        fontSize:16,
        fontFamily:FONTS.SemiBold,
        lineHeight:20,
      },
      invoiceInv:{
        color:'#1F9CEF',
        fontSize:14,
        fontFamily:FONTS.Medium,
      },
      invoiceAed:{
        color:'#153E73',
        fontSize:18,
        fontFamily:FONTS.SemiBold,
        height:20,
        paddingTop:2,
      },
      invoiceDate:{
        color:'#617191',
        fontSize:14,
        fontFamily:FONTS.Regular,
        paddingTop:3,
      },
      modal: {  
        backgroundColor : "#F2F7FC",   
        height: '90%' ,  
        width: '100%',  
        borderRadius:10,  
        borderWidth: 1,  
        borderColor: '#fff',    
        marginTop: 10,  
      },  
      topModelSection:{
        backgroundColor:'#1F9CEF',
        color:'#fff',
        padding:20,
        paddingBottom:80,
        zIndex:1,
      },
      closeIcon:{
        color:'#fff',
        height:40,
        paddingTop:10,
        paddingBottom:10,
        fontWeight:'bold',
        marginBottom:20,
      },
      modelPaidButton:{
        backgroundColor:'#36B152',
        borderWidth:1,
        borderColor:'#36B152',
        borderRadius:15,
        paddingVertical:5,
        paddingHorizontal:20,
        width:'20%',
        marginBottom:20,
      },
      modelInvoiceNo:{
        fontFamily:FONTS.SemiBold,
        color:'#fff',
        fontSize:16,
        fontWeight:'bold',
        marginBottom:20,
      },
      modelTitle:{
        fontFamily:FONTS.Regular,
        color:'#fff',
        fontSize:17,
      },
      modelAddress:{
        color:'#E2E6EF',
        fontSize:14,
        fontFamily:FONTS.Regular,
      },

      modelTopBoxSection:{
        padding:20,
        zIndex:5,
        marginTop:-90,
        borderRadius:10,
      },
      modelTopBoxContainer: {
        minHeight:100,
        width:'100%',
        borderColor:'#DCDCDC',
        backgroundColor:'white',
        borderWidth:1,
        marginTop:15,
        flexDirection:'row',
        borderRadius:10,
      },
      modelTwoSectionRow: {
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
      },
      modelOneBox:{
        padding:10,
        width:'50%',
      },
      modelTwoBox:{
        backgroundColor:'#F2F7FC',
        padding:10,
        width:'50%',
        borderColor:'#fff',
      },
      modelSingleBoxTitle:{
        color:'#1F9CEF',
        fontFamily:FONTS.Regular,
        fontSize:13,
        paddingBottom:2,
      },
      modelSingleBoxValue:{
        fontFamily:FONTS.SemiBold,
        fontSize:15,
        paddingBottom:15,
      },
      modelSingleBoxBottomValue:{
        fontFamily:FONTS.SemiBold,
        fontSize:15,
      },
      modelSingleBoxUniqValue:{
        fontFamily:FONTS.SemiBold,
        fontSize:19,
        paddingBottom:25,
      },
      modelSingleBoxDate:{
        color:'#1F222F',
        fontSize:12,
        fontFamily:FONTS.Regular,
        bottom:0,
      },
      modelImageBoxSectionRow:{
        display:'flex',
        flexDirection:'row',
      },
      modelImageBox:{
        padding:10,
        marginRight:10,
      },
      modelContentBox:{
        padding:10,
      },
      modelImageCircleBox:{
        justifyContent:'center',
        textAlign:'center',
      },
      modelImage:{
        height:70,
        width:70,
        borderRadius:50,
      },
      modelAmmountUpdateRow:{
        display:'flex',
        flexDirection:'row',
        borderColor:'#DCDCDC',
        borderWidth:1,
        borderRadius:5,
        marginTop:10,
      },
      modelAmmountUpdateBox:{
        padding:6,
      },
      modelAmmountUpdateBoxNumber:{
        padding:6,
        borderLeftColor:'#DCDCDC',
        borderRightColor:'#DCDCDC',
        borderLeftWidth:1,
        borderRightWidth:1,
      },
      mpText:{
        fontSize:14,
      },
      mpIcon:{
        paddingTop:2,
      },
      modelImageBoxTitle:{
        color:'#0F141A',
        fontFamily:FONTS.SemiBold,
        fontSize:15,
        paddingBottom:2,
      },
      modelImageBoxContent:{
        fontFamily:FONTS.Regular,
        color:'#617191',
        fontSize:12,
        paddingBottom:5,
      },
      modelImageBoxContentPackage:{
        fontFamily:FONTS.Regular,
        color:'#617191',
        fontSize:12,
      },
      modelImageBoxUniqValue:{
        fontSize:17,
        color:'#153E73',
        height:20,
        fontFamily:FONTS.SemiBold,
        marginTop:30,
      },
      invoiceButtonEdit:{
        borderWidth:1,
        borderColor:'#1F9CEF',
        borderRadius:15,
        paddingVertical:4,
        paddingHorizontal:15,
      },
      invoiceButtonEditText:{
        color:'#1F9CEF',
        fontSize:13,
        fontFamily:FONTS.SemiBold,
        textAlign:'left'
      },
      outletButton:{
        borderWidth:1,
        borderColor:'#1F9CEF',
        borderRadius:15,
        paddingVertical:4,
        paddingHorizontal:15,
        marginRight:20,
      },
      outletButtonText:{
        color:'#1F9CEF',
        fontSize:13,
        fontFamily:FONTS.SemiBold,
        textAlign:'left'
      },

});

export default GlobalStyles;